FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY app ./app
COPY stack.tsx ./
COPY next.config.mjs ./
COPY postcss.config.mjs ./
COPY tailwind.config.ts ./
COPY tsconfig.json ./
COPY main.ts ./

ENV NEXT_PUBLIC_SUPPRESS_HTTPS_COOKIE_ERROR=true

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build

ARG NEXT_PUBLIC_STACK_PROJECT_ID
ARG NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
ARG STACK_SECRET_SERVER_KEY
ARG SERVER_PORT
ARG PROXY_PORT

ENV NEXT_PUBLIC_STACK_PROJECT_ID=${NEXT_PUBLIC_STACK_PROJECT_ID}
ENV NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY}
ENV STACK_SECRET_SERVER_KEY=${STACK_SECRET_SERVER_KEY}
ENV SERVER_PORT=${SERVER_PORT}
ENV SERVER_HOST="host.docker.internal"
ENV PROXY_PORT=${PROXY_PORT}
ENV PROXY_HOST="localhost"

EXPOSE ${PROXY_PORT}

ENTRYPOINT ["node", "dist/main.cjs"]
CMD []